# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric (Minecraft 1.21)
minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.16.10
fabric_version=0.102.0+1.21

# Cloth Config / ModMenu
cloth_config_version=15.0.127
modmenu_version=11.0.3

# Mod
mod_version=1.0.0
maven_group=com.rate
archives_base_name=BoardcastMod